"""Mandatory disclaimer for AI-generated tax content (Circular 230 compliance)."""


CIRCULAR_230_DISCLAIMER = (
    "IMPORTANT: This analysis was generated by AI and is for informational purposes only. "
    "It does not constitute tax advice under Treasury Circular 230. Consult a licensed "
    "tax professional before making any tax decisions based on this information."
)

SHORT_DISCLAIMER = "AI-generated estimate. Not professional tax advice."


def wrap_with_disclaimer(content: str, short: bool = False) -> str:
    """Programmatically append disclaimer to AI-generated content.

    This is a mandatory wrapper -- all AI-generated tax content MUST
    pass through this function before being surfaced to users.
    """
    if not content:
        return content
    disclaimer = SHORT_DISCLAIMER if short else CIRCULAR_230_DISCLAIMER
    return f"{content}\n\n---\n*{disclaimer}*"
