#!/usr/bin/env python3
"""
Generate a Postman Collection v2.1 from the OpenAPI spec.

Usage:
    python scripts/export_postman.py [--input docs/api/openapi.json] [--output docs/api/postman_collection.json]

Reads docs/api/openapi.json (generated by export_openapi.py) and produces a
Postman collection with:
  - All endpoints grouped by OpenAPI tag
  - Pre-request script that injects {{base_url}} and {{jwt_token}} variables
  - Auth header set to Bearer {{jwt_token}}
"""
import json
import sys
import uuid
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = ROOT / "docs" / "api" / "openapi.json"
DEFAULT_OUTPUT = ROOT / "docs" / "api" / "postman_collection.json"


def _make_item(path: str, method: str, operation: dict) -> dict:
    """Convert a single OpenAPI operation to a Postman request item."""
    summary = operation.get("summary") or operation.get("operationId") or f"{method.upper()} {path}"
    description = operation.get("description", "")

    # Build URL with path params as Postman variables
    postman_path = path.replace("{", ":").replace("}", "")
    url_parts = [p for p in postman_path.split("/") if p]

    # Query params
    query_params = []
    for param in operation.get("parameters", []):
        if param.get("in") == "query":
            query_params.append({
                "key": param["name"],
                "value": "",
                "description": param.get("description", ""),
                "disabled": not param.get("required", False),
            })

    # Request body
    body = None
    request_body = operation.get("requestBody", {})
    if request_body:
        content = request_body.get("content", {})
        if "application/json" in content:
            schema = content["application/json"].get("schema", {})
            example_data = _schema_to_example(schema)
            body = {
                "mode": "raw",
                "raw": json.dumps(example_data, indent=2),
                "options": {"raw": {"language": "json"}},
            }
        elif "multipart/form-data" in content:
            body = {
                "mode": "formdata",
                "formdata": [],
            }

    item: dict[str, Any] = {
        "id": str(uuid.uuid4()),
        "name": summary,
        "request": {
            "method": method.upper(),
            "header": [
                {
                    "key": "Content-Type",
                    "value": "application/json",
                    "type": "text",
                }
            ],
            "url": {
                "raw": "{{base_url}}/" + "/".join(url_parts),
                "host": ["{{base_url}}"],
                "path": url_parts,
                "query": query_params,
            },
            "auth": {
                "type": "bearer",
                "bearer": [{"key": "token", "value": "{{jwt_token}}", "type": "string"}],
            },
            "description": description,
        },
        "response": [],
    }
    if body:
        item["request"]["body"] = body

    return item


def _schema_to_example(schema: dict) -> Any:
    """Recursively build a minimal example value from a JSON Schema fragment."""
    if not schema:
        return {}
    schema_type = schema.get("type")
    if "example" in schema:
        return schema["example"]
    if schema_type == "object":
        props = schema.get("properties", {})
        return {k: _schema_to_example(v) for k, v in props.items()}
    if schema_type == "array":
        return [_schema_to_example(schema.get("items", {}))]
    if schema_type == "string":
        return schema.get("default", "string")
    if schema_type in ("integer", "number"):
        return schema.get("default", 0)
    if schema_type == "boolean":
        return schema.get("default", False)
    return {}


def openapi_to_postman(spec: dict) -> dict:
    """Convert an OpenAPI 3.x spec dict to a Postman Collection v2.1 dict."""
    info = spec.get("info", {})

    # Group items by first tag
    tag_items: dict[str, list] = {}
    for path, path_item in spec.get("paths", {}).items():
        for method, operation in path_item.items():
            if method.upper() not in ("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"):
                continue
            tags = operation.get("tags", ["Untagged"])
            tag = tags[0] if tags else "Untagged"
            tag_items.setdefault(tag, []).append(_make_item(path, method, operation))

    folders = [
        {
            "id": str(uuid.uuid4()),
            "name": tag,
            "item": items,
        }
        for tag, items in sorted(tag_items.items())
    ]

    return {
        "info": {
            "_postman_id": str(uuid.uuid4()),
            "name": info.get("title", "API"),
            "description": info.get("description", ""),
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "version": info.get("version", "1.0.0"),
        },
        "variable": [
            {"key": "base_url", "value": "http://localhost:8000", "type": "string"},
            {"key": "jwt_token", "value": "", "type": "string"},
        ],
        "auth": {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{jwt_token}}", "type": "string"}],
        },
        "item": folders,
    }


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Export Postman collection from OpenAPI spec")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Path to openapi.json")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output path for Postman collection")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"ERROR: {input_path} not found. Run scripts/export_openapi.py first.", file=sys.stderr)
        return 1

    spec = json.loads(input_path.read_text(encoding="utf-8"))
    collection = openapi_to_postman(spec)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(collection, indent=2) + "\n", encoding="utf-8")

    endpoint_count = sum(
        len(methods)
        for methods in spec.get("paths", {}).values()
        if isinstance(methods, dict)
    )
    print(f"Postman collection written: {output_path.relative_to(ROOT)}")
    print(f"  Endpoints: {endpoint_count}")
    print(f"  Folders:   {len(collection['item'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
